In [1]:
from scipy.io import loadmat
import os
path=os.path.join('C:'+os.sep,'Users','divit','OneDrive','Desktop','IIT B courses','wids','archive','mnist-original.mat')
mnist = loadmat(path)
mnist_data = mnist["data"].T
mnist_label = mnist["label"][0]

print("completed")


completed


In [43]:
mnist_data[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  51, 159, 253,
       159,  50,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  48, 238,
       252, 252, 252, 237,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [20]:
print(mnist_data)
type(mnist_data(0))


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


TypeError: 'numpy.ndarray' object is not callable

In [18]:
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image
from IPython.display import Image

In [19]:
pil_img = Image(mnist_data(0))
display(pil_img)

TypeError: 'numpy.ndarray' object is not callable

In [23]:
import numpy as np 
from PIL import Image as im 
  
# define a main function 
def main(): 
  
    # create a numpy array from scratch 
    # using arange function. 
    # 28*28= 784 is the amount  
    # of pixels. 
    # np.uint8 is a data type containing 
    # numbers ranging from 0 to 255  
    # and no non-negative integers 
    array = np.arange(0, 784, 1, np.uint8) 
      
    # our array will be of width  
    # 784 pixels That means it  
    # will be a long dark line 
    print(mnist_data[0].shape) 
      
    # Reshape the array into a  
    # familiar resoluition 
    array = np.reshape(mnist_data[0], (28,28)) 
      
    # show the shape of the array 
    print(mnist_data[0].shape) 
  
    # show the array 
    print(mnist_data[0]) 
      
    # creating image object of 
    # above array 
    data = im.fromarray(mnist_data[0]) 
      
    # saving the final output  
    # as a PNG file 
    data.save('gfg_dummy_pic.png') 
  
# driver code 
if __name__ == "__main__": 
    
  # function call 
  main() 

(784,)
(784,)
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  51 159 253 159  50   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0  48 238 252 252 252 237   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  54 227 253 252 239 233 252  57   6   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  10  60 224 252 253 252 202  84 252
 253 122   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0 163 252 252 252 253 252 252  96 

In [47]:
from numpy import mean
from numpy import std
from matplotlib import pyplot as plt
from sklearn.model_selection import KFold
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD

ModuleNotFoundError: No module named 'tensorflow'

In [46]:
def load_dataset():
  trainX = mnist.load_data()
  # reshape dataset to have a single channel
  trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
  testX = testX.reshape((testX.shape[0], 28, 28, 1))
  return trainX

trainX = load_dataset()
# plot first few images
for i in range(9):
 # define subplot
 plt.subplot(330 + 1 + i)
 # plot raw pixel data
 plt.imshow(trainX[i], cmap=plt.get_cmap('gray'))
# show the figure
plt.show()


AttributeError: 'dict' object has no attribute 'load_data'

In [49]:
!pip install tensorflow

^C


In [50]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)

c = tf.add(a, b)

with tf.Session() as sess:
    result = sess.run(c)
    print(result)

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

ImportError: initialization failed